baseURL = "https://drajad.netlify.com/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Drajad Blog"
[markup.goldmark.renderer]
unsafe = true
